name: Update Incendies

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Télécharger le JSON
        run: |
          curl -L \
          -A "Mozilla/5.0" \
          https://incendieencours.fr/data/fire_events_live.json \
          -o incendies.json

      - name: Vérifier
        run: |
          ls -lh
          head incendies.json
